### ISSUE TITLE
Is there a pretrained model for fine-tunning？

### ISSUE THREAD

**Issue by miraclewkf** [gaohuang/MSDNet#3]
Is there a pretrained model for fine-tunning？

**Comment by gaohuang** [comment]
Hi, we are planning to release pretrained models next month. Or you can send me your email, and I can share you an internal version now.

**Comment by miraclewkf** [comment]
wkf8092 at 163.com, thanks.

**Comment by gaohuang** [comment]
Here are the links to two MSDNets used in our paper:
http://www.cs.cornell.edu/~gaohuang/models/msdnet--step=7--block=5--growthRate=16.t7 
http://www.cs.cornell.edu/~gaohuang/models/msdnet--step=4--block=5--growthRate=16.t7 

PS: You need to download the latest version of this repo to load the pretrained models.

**Comment by stevelaskaridis** [comment]
@gaohuang, the links provided do not seem to work, as some kind of redirection is happening from cornell to your domain name.
Could you please revise them or provide an alternative download method of pre-trained models?

**Comment by gaohuang** [comment]
Hi, please try the following link:
https://www.dropbox.com/sh/n0xxbgvsql0rqna/AADrVbTVKyo4YVN-HqmjPWs5a?dl=0

**Comment by stevelaskaridis** [comment]
HI @gaohuang,

Thank your for updating the link.
I have been trying to further train your given models, but unfortunately it did not work.

I tried to run the script from the top-level README: 
```
th main.lua -dataset imagenet -testOnly true -resume <path-to-.t7-model> -data <path-to-image-net-data> -gen <path-to-validation-set-indices>
```

More specifically, in the **checkpoints.lua** file, the resume option seems to be searching for a couple of things missing from the dropbox shared directory, such as the ***latest.t7** or the `optimFile`.
As a result, the function `checkpoint.latest` fails and returns nil.

Am I potentially missing something?

**Comment by gaohuang** [comment]
Sorry, it seems that there is a mistake in the command line from the README. Could you try replacing "resume" by "retrain"?

**Comment by stevelaskaridis** [comment]
Hi @gaohuang,
I tried that, but the next error comes from `./models/init.lua:31`:
```
Attempt to call method 'type' (a nil value)
```

Here is the full command that I am running:
```
th main.lua -dataset imagenet -testOnly true -retrain ./pretrained/imagenet_withvalid.t7 -data <path-to-image-net-data> -gen <path-to-validation-set-indices>
```
I am using Torch7 in nvidia docker.
I also tried different precisions, but same output.

**Comment by gaohuang** [comment]
The argument passed to -retrain should be the model file, e.g., "msdnet--step=4--block=5--growthRate=16.t7".

The file "imagenet_withvalid.t7" is for saving data index, and should be put under a "gen" folder.

**Comment by stevelaskaridis** [comment]
Hi @gaohuang,

Thank you for the input. That seems to solve that.
However, it seems like the model is serialised from a different version of the model than the one in the repository. The error now is:
```
unknown Torch class <nn.JointTrain>
```
This seemed to have changed from `JointTrain` to `JointTrainModule` in commit fa30abe2b43e7a6f6b3fde52b773357b541045c7.
After reverting that change, I stumbled upon a similar issue, but found no such class in the history:
```
unknown Torch class <nn.NN_Layer_initial>
```

I would appreciate your help.

**Comment by gaohuang** [comment]
Could you try this link https://www.dropbox.com/sh/elnyjl4xdi4zyas/AACxCdjV-RWYrHYfbz61FFDma?dl=0?

**Comment by stevelaskaridis** [comment]
Hi @gaohuang,

That worked great. Thank you for your valuable assistance in setting it up.
