### ISSUE TITLE
Why is the number of output channels of the first convolution in the first layer 32?

### ISSUE THREAD

**Issue by niranjantdesai** [gaohuang/MSDNet#7]
According to Appendix A in the [paper](https://openreview.net/pdf?id=Hk2aImxAb), for the CIFAR datasets, the number of output channels of the three scales is set to 6, 12 and 24 respectively. However, `nChannels` is set to 32 in [msdnet.lua](https://github.com/gaohuang/MSDNet/blob/master/models/msdnet.lua) if `initChannels` is not set in the arguments. This means that the number of output channels in the first layer for the three scales is 32, 64 and 128 respectively according to the default growth rate 1-2-4-4. Why is there a difference between the implementation details in the paper and the code?

**Comment by gaohuang** [comment]
This option was added for ImageNet experiment in a later commit (https://github.com/gaohuang/MSDNet/commit/fa30abe2b43e7a6f6b3fde52b773357b541045c7), and the default value was set for ImageNet models. The descriptions and results in the paper are not affected. (Note that the initChannels specifies the number of channels of the very first conv layer, and it is different from the growth rate.)

I have fixed this issue. Thanks for pointing out.

**Comment by niranjantdesai** [comment]
According to the latest update in [msdnet.lua](https://github.com/gaohuang/MSDNet/blob/master/models/msdnet.lua),
```lua
if opt.dataset == 'cifar10' or opt.dataset == 'cifar100' then
      nChannels = opt.initChannels>0 and opt.initChannels or 16
   elseif opt.dataset == 'imagenet' then
      nChannels = opt.initChannels>0 and opt.initChannels or 64
```

According to my understanding, the MSDNet used for the CIFAR datasets has three scales with 6, 12 and 24 feature maps at each layer and that used for ImageNet has four scales producing 16, 32, 64 and 64 feature maps at each layer. However, the values in the code are different (16 and 64 instead of 6 and 16 respectively). Is the first layer an exception to this rule?

**Comment by gaohuang** [comment]
Right, the very first layer has a slightly different structure (its input only has one scale).

**Comment by ShoufaChen** [comment]
@gaohuang  @niranjantdesai  
From the latest [msdnet.lua](https://github.com/gaohuang/MSDNet/blob/master/models/msdnet.lua#L15),
the very first layer output channel is 64, 128, 256, 256 channels for the 4 scales on ImageNet. 
However, I found in the model checkpoint [msdnet--step=4--block=5--growthRate=16.t7](http://www.cs.cornell.edu/~gaohuang/models/msdnet--step=4--block=5--growthRate=16.t7) , the very first layer's channels ifs 32, 64, 128, 128 for the 4 scales, respectively.

Does it mean I can't use the default argument  [-initChannels](https://github.com/gaohuang/MSDNet/blob/master/opts.lua#L64) and should specify it as 32 when use ImageNet?

**Comment by gaohuang** [comment]
Right. In fact, we usually let the first layer to be twice the width of subsequent layers, following the design of DenseNet.
